"""add data to user

Revision ID: 781a3bf865bc
Revises: 60e8645fc818
Create Date: 2025-11-09 21:40:16.493079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '781a3bf865bc'
down_revision: Union[str, None] = '60e8645fc818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('data', sa.JSON(), nullable=False), schema='bday_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'data', schema='bday_time')
    # ### end Alembic commands ###
