"""add day0 to notif

Revision ID: f29cefedc091
Revises: 781a3bf865bc
Create Date: 2025-11-10 00:03:11.264486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29cefedc091'
down_revision: Union[str, None] = '781a3bf865bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('day_0', sa.Boolean(), nullable=False), schema='bday_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'day_0', schema='bday_time')
    # ### end Alembic commands ###
